### ISSUE TITLE
Fixed bug in how scene build index is calculated

### ISSUE THREAD

**Issue by joshuawilde** [edcasillas/unity-common-utils#12]
Finally took a look at this because it caused us some issues over the years, but turns out it is because the build index isn't taken into account properly if there are scenes prior to it that are disabled. I don't have time to file a proper PR atm, but the main change is to the loops over the EditorBuildSettings.scenes in both the scripts attached (BuildUtils and SceneData)

Everything else in CommonUtils seems to still be working great though!

[Archive.zip](https://github.com/edcasillas/unity-common-utils/files/10302283/Archive.zip)

**Comment by edcasillas** [comment]
Thanks for your contribution Josh! I just applied these changes on master so they will be available when you update the CommonUtils.
